backend:
  name: git-gateway
  branch: main # Yahan apni Github branch ka naam check kar lena (main ya master)

media_folder: "assets" # Images yahan save hongi
public_folder: "assets" # Frontend images ko yahan se read karega

collections:
  - name: "store"
    label: "Store Management"
    files:
      - file: "data/products.json" # CMS sara data is ek JSON file mein save karega
        name: "products_catalog"
        label: "Products Catalog"
        fields:
          - name: items
            label: All Products
            identifier_field: name
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Category", name: "category", widget: "select", options: ["men", "women", "kids"] }
              - { label: "Price", name: "price", widget: "number", value_type: "int" }
              - { label: "Main Image", name: "image", widget: "image" }
              - { label: "Sizes", name: "sizes", widget: "select", multiple: true, options: ["S", "M", "L", "XL"] }
              - { label: "Colors Available", name: "colors", widget: "list", field: {label: "Color", name: "color", widget: "string"} }
              - { label: "Badge (e.g., Bestseller)", name: "badge", widget: "string", required: false }
              - { label: "Description", name: "description", widget: "text" }
              - { label: "Shipping", name: "shipping", widget: "string", default: "2-3 Business Days" }
              - name: "colorImagesList"
                label: "Images for Specific Colors"
                widget: "list"
                required: false
                fields:
                  - { label: "Color Name (must match exactly)", name: "colorName", widget: "string" }
                  - { label: "Image", name: "imgUrl", widget: "image" }